version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log  # Prepended with correct directory in application code
        maxBytes: 20971520 # 20MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log  # Prepended with correct directory in application code
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log  # Prepended with correct directory in application code
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    urllib3.connectionpool:
        level: WARNING
    matplotlib:
        level: WARNING
    botocore:
        level: INFO

root:
    level: DEBUG
    handlers: [debug_file_handler, info_file_handler, error_file_handler]
